import FooterComponent from "@/components/footer/FooterComponent";
import HeaderComponent from "@/components/header/HeaderComponent";
import Providers from "@/redux/Providers";
import { getServerSession } from "next-auth";

// import './globals.scss'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
        <Providers>
          <HeaderComponent session={session}/>
          {children}
          <FooterComponent />
        </Providers>
      </body>
    </html>
  );
}
